/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
//#pragma DATA_SECTION (COEFFS, "coeff_sect");

	

Int16 COEFFS[12] = {-3030, 1592, 2733, 4236, 5607, 6416, 6416, 5607, 4236, 2733, 1592, -3030};// These filter coefficients are used for first exerscise.

